global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-api'
    static_configs:
      - targets: ['auth-api:9200']
    metrics_path: /stats

  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:9000']
    metrics_path: /metrics

  - job_name: 'presence-service'
    static_configs:
      - targets: ['presence-service:3002']
    metrics_path: /metrics
